name: Android CI - Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK tools and required components
        uses: google-github-actions/setup-android@v2
        with:
          api-level: 33
          components: |
            build-tools;30.0.3
            platform-tools
            platforms;android-33

      - name: Make gradlew executable
        run: chmod +x android-app/gradlew

      - name: Build debug APK
        working-directory: android-app
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android-app/app/build/outputs/apk/debug/app-debug.apk
